### ISSUE TITLE
Only recompile, when LESS files has changed

### ISSUE THREAD

**Issue by martinthogersen** [gdub22/ember-cli-less#10]
The LESS compiler runs each time a file has changed, even if no LESS files have been touched:

```
file changed templates\admin\index.hbs

Build successful - 11018ms.

Slowest Trees                  | Total
-------------------------------+---------
LessCompiler                   | 2218ms
Funnel: App JS Files           | 1117ms
Concat: Vendor                 | 1057ms
SourcemapConcat                | 703ms
SourcemapConcat                | 645ms
Concat: Test Support JS        | 637ms
TreeMerger (vendor)            | 602ms
ES6Modules                     | 578ms
```

Is it possible to only run LESS recompile, when a LESS file has been edited? That would save a lot of time.

**Comment by gdub22** [comment]
@martinthogersen I can't reproduce this.  Only changing a less file triggers a less rebuild.  Could be a problem with a specific ember-cli version?  Working well on 0.1.15 and all previous versions.

**Comment by martinthogersen** [comment]
I upgraded to version 0.2.0-beta.1 after writing the previous comment, and the LessCompiler still runs for every change:

```
file changed routes\admin\index.js

Build successful - 7793ms.

Slowest Trees                  | Total
-------------------------------+------------
LessCompiler                   | 1619ms
Funnel: App JS Files           | 756ms
TreeMerger (vendor)            | 504ms
Concat: Vendor                 | 488ms
```

**Comment by jasonmit** [comment]
This is a known issue we have seen in the past, not an issue within ember-cli-less specifically though.  Stefan is working on some logging so you can easily track down what is touching the tree, causing the cache writer to invalidate the style tree.

It may be better to open to issue in broccoli-less-single repo for tracking purposes.

/cc @stefanpenner

**Comment by stefanpenner** [comment]
@jasonmit ya, I tracked it down to sourceMapConcat invalidating the tree. I have been busy because of emberconf but @rwjblue may have time to look into it today, if not I will look into it early this next week.

(currently driving back from portland, so no only LTE on my phone not my laptop)

**Comment by martinthogersen** [comment]
@stefanpenner Can I track the progress somewhere?

**Comment by stefanpenner** [comment]
not currently, it is quite literally in every related project.

**Comment by martinthogersen** [comment]
Alright thanks. Keep up the good work :+1:

**Comment by stefanpenner** [comment]
basically, I got blocked by that stupid glob/rimraf + npm issue. Now that that is resolved I can resume work. It was just wide-spread because it involves updating literally everything :P

**Comment by martinthogersen** [comment]
Awesome! Does that mean that this issue is resolved?
https://github.com/broccolijs/broccoli/issues/232

**Comment by DENIELER** [comment]
@martinthogersen no, it still actual for me, at least, even after update to new version (

**Comment by g-cassie** [comment]
I have experienced this issue for a couple months. I think I have used the following versions of ember-cli in that time:  `0.12.x`, `0.15.x`, `0.2.1`.  This was not an issue prior to upgrading to `0.12.x` but unfortunately I can't recall what cli version I had prior to that.
