### ISSUE TITLE
broccoli-less-single less parser upgraded from 1.x to 2.x

### ISSUE THREAD

**Issue by jasonmit** [gdub22/ember-cli-less#12]
Just a friendly note that we've upgraded the Less parser within broccoli-less-single.  

Nothing stands out as a breaking change (http://lesscss.org/usage/#v2-upgrade-guide-programmatic-usage), but the latest broccoli-less-single version is now 0.2.0.

Notifying you since your version constraints would be pulling in that change.

Thanks

**Comment by gdub22** [comment]
@jasonmit thanks for the heads up! Working on an update now.  Currently, it will still pull in 1.x less as a dependency of broccoli-less-single at 0.1.5

**Comment by timohofmeijer** [comment]
:+1: (This update will resolve the issue where the express-server craps out on less compilation errors, which becomes quite painfull on larger projects)

**Comment by gdub22** [comment]
closed via 4178e3e3a6dc5e9c3e1a808c04b51066500aaa7a
