### ISSUE TITLE
LessCompiler runs for every build in watch mode

### ISSUE THREAD

**Issue by g-cassie** [gdub22/ember-cli-less#15]
When running `ember build --watch` the `LessCompiler` task runs during every single build even when no changes have been made to any `.less` files.  This significantly increases the total build time because the task takes 0.5-2.5 seconds and the rest of the build takes about 0.5-1.5 seconds.  

I am not sure whether this is a problem with ember-cli, ember-cli-less or my config.  Would appreciate some help on how I can debug this and figure out the issue.

**Comment by gdub22** [comment]
Should not be an issue with this addon.
See https://github.com/gdub22/ember-cli-less/issues/10

**Comment by g-cassie** [comment]
Sorry should have noticed that issue before I posted. I'll close this and comment over there if necessary.
