### ISSUE TITLE
option confusion

### ISSUE THREAD

**Issue by stefanpenner** [gdub22/ember-cli-less#16]
https://github.com/gdub22/ember-cli-less/blob/master/index.js#L38 these options are for configuring the client-side app not the build tool

**Comment by gdub22** [comment]
@stefanpenner ya, shouldn't be there. @azirbel any reason you added that in your PR? https://github.com/gdub22/ember-cli-less/pull/14

**Comment by azirbel** [comment]
not a good reason; I copied it from https://github.com/aexmachina/ember-cli-sass/blob/master/index.js#L42. Sorry =/

**Comment by gdub22** [comment]
@azirbel no worries, easy to remove.  @stefanpenner you may want to open an issue over there too if this is a concern.

**Comment by aexmachina** [comment]
Hmmn, interesting. I received [a PR](https://github.com/aexmachina/ember-cli-sass/pull/22) that implemented the required changes for addons that were introduced in ember-cli@0.2.0. This PR also moved the configuration out of the Brocfile based on discussion with @rwjblue: http://cl.ly/image/1T3L3l0d1B1w. I thought it was strange but after some investigation decided that I'd follow Robert's instruction.

Can I get clarification of where the config for this should live? Is it "build tool = Brocfile, client app = config/environment.js"?

**Comment by stefanpenner** [comment]
@aexmachina yes. Although the build-tool config is shitty right now. We plan to improve.

**Comment by aexmachina** [comment]
Okay, I'll move it back to the Brocfile then. Probably should have sought clarification from @rwjblue in the first place.

**Comment by gdub22** [comment]
Resolved by #21
