### ISSUE TITLE
sourceMap: true, requires source-map module (but this project does not include it)

### ISSUE THREAD

**Issue by stefanpenner** [gdub22/ember-cli-less#18]
https://github.com/gdub22/ember-cli-less/blob/master/index.js#L40-L42

**Comment by gdub22** [comment]
Source maps worked here I presume until source map support landed in directly in ember-cli?  Any references would be helpful to get this back up. @stefanpenner

**Comment by stefanpenner** [comment]
> Source maps worked here I presume until source map support landed in directly in ember-cli?

this sentence confuses me.

**Comment by gdub22** [comment]
Less source maps were working in this plugin.  They no longer do.  I'm guessing they broke due to an update in ember-cli.  What is the source-map module?

**Comment by stefanpenner** [comment]
it appears npm trolled me, and for some-reason did not install the optional dependency less has on `source-map` module

**Comment by xcskier56** [comment]
Is this fixed? I'm using 1.3.2 and not getting any source maps. On ember 1.11.1, ember-cli 0.2.3.

When I downgrade to version 1.1.1, and get brocoli-less-single v 0.1.5, the source maps work.
