### ISSUE TITLE
sourceMaps don't seem to work

### ISSUE THREAD

**Issue by akatov** [gdub22/ember-cli-less#23]
running version 1.3.2 on node v0.12. Sourcemaps aren't being generated. config:

```javascript
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

var app = new EmberApp({
  lessOptions: {
    paths: [
      'bower_components/bootstrap/less'
    ],
    sourceMap: true
  }
});
```

**Comment by xcskier56** [comment]
I had this same issue. I downgraded to `1.1.1` and that brought them back.

**Comment by gdub22** [comment]
Confirm they are broken.  ember-cli-less 1.2.0 upgraded its dependencies (broccoli-less-single / less 2.x) and there is an issue there, which I am working through. Reference: https://github.com/gabrielgrant/broccoli-less-single/issues/23

**Comment by gdub22** [comment]
@akatov @xcskier56 fixed in 1.3.3
thanks for reporting

**Comment by akatov** [comment]
thank you for fixing! :+1:

**Comment by xcskier56** [comment]
Really appreciate the quick response, thanks!
