### ISSUE TITLE
Include the complete stack trace in the browsers build error message

### ISSUE THREAD

**Issue by petetnt** [gdub22/ember-cli-less#25]
When there's an LESS parse error, the console shows the following: 

``` bash
ParseError: Unrecognised input in C:\app\tmp\tree_merger-tmp_dest_dir-TgNLTjbg.tmp\app\styles\_general.less on line 348, column 9:
347
348         &.selected {
349             border: 2px solid @some-variable;

Unrecognised input
```

Which is very useful. However, the browser itself only shows the following:

``` html
Build error
Unrecognised input
```

Compare this to a failing template:

(Browser and console)
```
Build error

app/templates/components/component.hbs (in  C:\app\tmp\tree_merger-tmp_dest_dir-3JBdsU4d.tmp)

each doesn't match if - 2:7
Error
    at C:\app\bower_components\ember\ember-template-compiler.js:3440:27
    at requireModule (C:\app\bower_components\ember\ember-template-compiler.js:66:65)
    at requireModule (C:\app\bower_components\ember\ember-template-compiler.js:62:24)
    at requireModule (C:\app\bower_components\ember\ember-template-compiler.js:62:24)
    at requireModule (C:\app\bower_components\ember\ember-template-compiler.js:62:24)
    at requireModule (C:\app\bower_components\ember\ember-template-compiler.js:62:24)
    ... and so on
```

Windows 8.1., `ember-cli-less` v1.3.3, ember-cli 0.2.5.

**Comment by gdub22** [comment]
I looked through the available addon hooks and ember-cli source and It doesn't look possible at the moment.  IMO it would be more desirable for the build to just fail and server not start at all, and thus just rely on the console errors.

**Comment by gdub22** [comment]
I found that it doesn't display in the browser because the error is missing the stack trace.  Ideally we should have them add error.stack in node less.  I fixed it here https://github.com/gdub22/ember-cli-less/commit/20bb59af4ca818abd693fc5a01ac17e478d20432 by having it print the stringified error object.

**Comment by petetnt** [comment]
Awesome :+1 

I can check out that upstream issue.
