### ISSUE TITLE
Can't specify lessOptions.paths in addon

### ISSUE THREAD

**Issue by orochi235** [gdub22/ember-cli-less#36]
We're having a bit of a weird issue with getting ember-cli-less to respect the `lessOptions.paths` setting in our ember-cli addon. We're simply trying to bundle all of our common stylesheets (in Less format) into a private Bower module, and then expose that module via the `paths` configuration option.

We're on an older version of ember-cli (0.2.7), but what we're doing is pretty straightforward. In fact, the following is the entire body of our Brocfile:

```javascript
var EmberAddon = require('ember-cli/lib/broccoli/ember-addon');

var app = new EmberAddon({
    loader: 'vendor/loader.js',

    lessOptions: {
        paths: ['bower_components/our-custom-css-component/']
    }
});

module.exports = app.toTree();
```

Tried running this on several versions of ember-cli-less, including 1.4.0, and have gotten several different error messages. The most recent one stems from `app.options` not existing, and `app.app.options` seemingly containing the data that's expected to be found on `app.options`. We made a one-line change to index.js that fixes the issue, but it feels a bit kludgy, and likely doesn't address the root cause.

```javascript
  lessOptions: function() {
    var env = process.env.EMBER_ENV;
    var app = this.app;
    if (!app.options) app = app.app; // <- this is the fix we added
    var options = (app && app.options && app.options.lessOptions) || {};

    if ((options.sourceMap === undefined) && (env === 'development')) {
      options.sourceMap = true;
    }

    return options;
  }
```

It looks like other addons have experienced similar problems, for what it's worth: https://github.com/ef4/ember-browserify/issues/29

Any help you could provide would be much appreciated. Happy to offer additional details as needed, or submit this as a PR if you'd like to merge it. Thanks!

**Comment by knownasilya** [comment]
Sounds like a workaround that we'd want to implement, since ember-cli hasn't been moving on addon-to-addon usage. 

I think we'd take the PR, just make sure to leave a comment for why the change is there and that it should be removed once support exists.

**Comment by knownasilya** [comment]
Closing since PR was merged.
