### ISSUE TITLE
Fixed Source Map generation when multiple input/output paths are used.

### ISSUE THREAD

**Issue by mkempe** [gdub22/ember-cli-less#38]
Hey there,

first of all, many thanks for the plugin.

Could you please look over https://github.com/gabrielgrant/broccoli-less-single/pull/28 and give feedback, this probably fixes https://github.com/gdub22/ember-cli-less/issues/32 and makes

```javascript
lessOptions: {
  mergeTrees: {
    overwrite: true
  }
}
```

no longer necessary.

Thanks.

Maik

PS: If the pull request is accepted, i will make a pull request, which bumps the version of `ember-cli-less` and updates the README.

**Comment by knownasilya** [comment]
Could you create the PR based on your PR branch, so we can test ahead of time? Then it could be updated to change to the new version of less-single.

**Comment by mkempe** [comment]
Hey Ilya,

thanks for your feedback. I created the PR and close this issue.
