### ISSUE TITLE
CSS not refreshed with ember server when children less are modified

### ISSUE THREAD

**Issue by Tuizi** [gdub22/ember-cli-less#48]
My Ember2 project is configured to use pods.
So I have this structure:

├── ember-pod/
│    ├── app/
│        ├── adapters/
│        ├── models/
│        ├── pods/
│        │   ├── components/
│        │   │   ├── list-item/
│        │   │   │    ├── style.less
│        │   ├── route1/
│        ├── styles/
│            ├── app.less

In app.less I have:
`@import app/pods/components/list-item/style`

Then I run: `ember server`

When I modify the app.less file, the change is detected, the browser is refreshed, the CSS includes my change.
When I modify the style.less file, the change is detected, the browser is refreshed, the CSS **does not** includes my change. (_I have to stop and restart ember server_)

Is there something to do in the configuration?

**Comment by knownasilya** [comment]
The current version of PODs does not support having styles in the PODs structure. All styles must be in the styles folder, and only app.* is consumed i.e. import sub files into app.less

**Comment by Tuizi** [comment]
Is it an issue with this package or with Ember?

**Comment by knownasilya** [comment]
With ember-cli, not so much an issue, just not implemented yet. Check out https://github.com/ebryn/ember-component-css, it might help in the interim.
