### ISSUE TITLE
Semantic-UI LessCompiler Undefined Issues

### ISSUE THREAD

**Issue by cwilli34** [gdub22/ember-cli-less#52]
So I have the following in my theme.config:

```
/*******************************
            Folders
*******************************/

/* Path to theme packages */
@themesFolder : 'src/themes';

/* Path to site override folder */
@siteFolder  : 'app/styles/site';

/*******************************
         Import Theme
*******************************/

@import "app/styles/theme.less";

/* End Config */
```

If I copy the `themes` folder and put it in the `app/styles` directory and then change `@themesFolder` to point to `app/styles/themes`, I get this after doing ember server:

```
NameError: variable @positiveTextShadow is undefined in bower_components/semantic-ui/src/definitions/elements/button.less on line 3212, column 16:
3211   color: @positiveTextColor;
3212   text-shadow: @positiveTextShadow;
3213   background-image: @coloredBackgroundImage;

File: bower_components/semantic-ui/src/definitions/elements/button.less (3212)
The Broccoli Plugin: [LessCompiler] failed with:
undefined
```

So what am I doing wrong?  I am using the ember-cli-less package.  I have the following in my ember-cli-build.js file:

```
var app = new EmberApp(defaults, {
        lessOptions: {
            paths: [
                'bower_components/semantic-ui',
                'app/pods/components'
            ]
        },
        outputPaths: {
            app: {
                css: {
                    app: "assets/css/project.css"
                },
                js: "assets/js/project.js"
            },
            vendor: {
                css: "assets/css/vendor.css",
                js: "assets/js/vendor.js"
            }
        },
        SemanticUI: {
            css: false,
            javascript: true,
            fonts: true,
            cssPath: "assets/css"
        },
    });
```
This happens only with @import "src/semantic" in the app.less file.  If I remove that, the error doesn't occur, but then I loose my Semantic-UI definitions of course, so that isn't an option.

I tried getting this looked at on the Semantic-UI-ember repository, but they didn't help and said it sounds like a ember-cli compiler issue.  What is the correct way to point to your own custom `themes` folder?

**Comment by knownasilya** [comment]
Does semantic-ui import the less styles automatically? Seems like your import assumes that, other wise you'd have to import from the node_modules or bower_components folders depending where it is..

**Comment by cwilli34** [comment]
> This happens only with `@import "src/semantic"` in the app.less file. If I remove that, the error doesn't occur, but then I loose my Semantic-UI definitions of course, so that isn't an option.

I do the import in the app.less file.  It gets the information from semantic.less in the `bower_components /semantic-ui/src` directory.  The semantic.less file imports all the definitions.  I have no issues applying themes in the theme.config file, but it gets the themes from `bower_components/semantic-ui/src/themes`.  I should be able to have custom themes and override themes files by giving another path to `@themesFolders`.  

Otherwise I am not sure what you mean.

**Comment by cwilli34** [comment]
Here is a link to an example project that is the only configuration I can find.  Even still, I have had to configure the actual index.js file in my semantic-ui-ember directory under node_modules to get this to work correctly with font and icon files.  

[https://github.com/nathanpalmer/example-semantic-ui-ember-cli](https://github.com/nathanpalmer/example-semantic-ui-ember-cli)

**Comment by knownasilya** [comment]
Try importing `bower_components /semantic-ui/src/semantic` instead.

**Comment by cwilli34** [comment]
It still gives the same error. I will try to set-up an example repo and post the link.

**Comment by Unnumbered** [comment]
I got the same error when I changed semantic-ui version from 2.1.8 to 2.2.x.
I don't remember how to fix it, but now my 'theme.config' looks like this:

```
..same variable definitions..

/* Path to theme packages */
@themesFolder : 'src/themes';

/* Path to site override folder */
@siteFolder  : 'site';

@import 'app/styles/theme.less';
```

I hope it's useful to someone.

**Comment by cwilli34** [comment]
@Unnumbered ~ I am guessing it has to do with changes to the `bower_components/semantic-ui/src/_sites` and  `bower_components/semantic-ui/src/themes` folders for you when you updated.  If you update the Semantic-UI version, then those changes in the `src` directory are going to give you the LessCompiler `undefined` issues.  You have to recopy (overwrite), or delete the old and copy the new `_sites` and `themes` folders into you `app/styles/` directory every time you update.  At least copy and replace all the files that end with `.variables`.  But I noticed that there was actually a couple files ending with the `.overrides` extension also that had changes, which is not ideal at all actually.  The override files should be empty and for the developer to use and not be changed during updates. There will also be a lot of added files, along with changes to all the font files.  So you might actually have to compare the folders in your `app/styles/` path to the `src` path every time Semantic-UI is updated.

That was kind of my issue.  Except I didn't do an update of Semantic-UI, and I deleted the folders in my `app/styles` path and copied the folders from the  `bower_components/semantic-ui/src/` path several times trying to debug and figure out the issue.  Yet today I used Meld, did a directory comparison, and behold (!!) the `sites` and `themes` folders in my `app/styles/` path where not the same as the `_sites` and `themes` folders in the `bower_components/semantic-ui/src` path.  Not sure why that was, or what happened, but it was obviously something on my end, and not anything to do with semantic-ui-less, or ember-cli-less. 

So now I am effectively using the following paths: 

```
/*******************************
            Folders
*******************************/

/* Path to theme packages */
@themesFolder : 'app/styles/themes';

/* Path to site override folder */
@siteFolder  : 'app/styles/site';

/*******************************
         Import Theme
*******************************/

@import "app/styles/theme.less";

/* End Config */
```

 I am closing this issue.
