### ISSUE TITLE
Running the dummy app in an Ember addon project can't find app/styles/app.less

### ISSUE THREAD

**Issue by QuantumInformation** [gdub22/ember-cli-less#9]
I'm trying to test an `Ember addon` project by running ember server inside an addon project. This runs the dummy app. However I am not getting my less files automatically being build with the ember-cli-less functionality (expecting ` /app/styles/app.less`):

Some files I have:

    /addon-project
      /app
        /styles
          /less
          app.less
      /dist
      /assets
         dummy.js
         dummy.css
      /tests
        /dummy

However I am getting an error when I run ember server:

    version: 0.1.15
    Could not find watchman, falling back to NodeWatcher for file system events

    Livereload server on port 35730
    Serving on http://0.0.0.0:4201/
    File not found: /app/styles/app.less
    in any of the following include paths:
      /Users/me/github/ember-addons/header/tmp/tree_merger-tmp_dest_dir-qEC1hODR.tmp
    Error: File not found: /app/styles/app.less

**Comment by aboma** [comment]
I have this issue as well in my add-on.

**Comment by gdub22** [comment]
@QuantumInformation @aboma I'm pretty sure this is an issue with ember-cli itself.
See: https://github.com/ember-cli/ember-cli/issues/2363, https://github.com/ember-cli/ember-cli/issues/2354, https://github.com/ember-cli/ember-cli/pull/2381

**Comment by aboma** [comment]
This issue is solved now in EmberCLI >= 0.2.0. Install the addon and add it under the dependencies hash.

However, now I get the following error:

Cannot read property 'lessOptions' of undefined
TypeError: Cannot read property 'lessOptions' of undefined at Class.module.exports.lessOptions (C:\src\TUI\SPCIQ\Presentation\widget-framework\node_modules\ember-cli-less\index.js:42:49)

For addons, the options object appears to be null for some reason. Other addons such as the ember-cli-sass compiler read the options from the ENV variable first.

**Comment by gdub22** [comment]
@aboma can you verify if you're using the latest version 1.3.1 and defining lessOptions in your Brocfile?

**Comment by stavarotti** [comment]
@gdub22 I am seeing this issue as well.  What is the recommended way to use ember-cli-less in an addon, along with using the dummy app?  The readme doc is quite sparse when it comes to the addon section.

**Comment by aboma** [comment]
Yes, I am using version 1.3.1 and defining lessOptions in the Brocfile. The problem appears to be that the app object exists but the app.options object does no, for some reason, when compiling in an addon. Perhaps there is an addon object as well?

I made a PR that fixes the issue by putting the lessOptions on the config object, but it does make more sense for it to be in the Brocfile.

**Comment by gdub22** [comment]
@aboma @stavarotti I just investigated this and got it working.  I'll have a small patch and more detailed directions in the next couple hours.

**Comment by gdub22** [comment]
@aboma @stavarotti I just released 1.3.2 with a fix for addon's dummy app.  I also made the directions clearer: https://github.com/gdub22/ember-cli-less#usage-in-addons

**Comment by aboma** [comment]
Thanks!

**Comment by stavarotti** [comment]
@gdub22 Awesome.  Works wonderfully now.
